version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orders_app
    volumes:
      - .:/app
    command: ["python", "orders_analysis.py"]

  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: orders_tests
    volumes:
      - .:/app
    command: ["pytest", "test_orders_analysis.py"]
